name: Greetings

on:
  workflow_dispatch:

jobs:
  install-pip-deps:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3.5.2
        with:
          clean: false
      - uses: actions/checkout@v3.5.2
        with:
          repository: "mtararujs/python-greetings"
          path: "deploy-dir"
          clean: false
      - uses: ./.github/actions/install

  deploy-to-dev:
    runs-on: self-hosted
    needs: [install-pip-deps]
    steps:
      - uses: actions/checkout@v3.5.2
        with:
          clean: false
      - uses: actions/checkout@v3.5.2
        with:
          repository: "mtararujs/python-greetings"
          path: "deploy-dir"
          clean: false
      - uses: ./.github/actions/deploy
        with:
          port: 7001
          env: "dev"

  tests-on-dev:
    runs-on: self-hosted
    needs: [deploy-to-dev]
    steps:
      - uses: actions/checkout@v3.5.2
        with:
          clean: false
      - uses: actions/checkout@v3.5.2
        with:
          repository: "mtararujs/course-js-api-framework"
          path: "test-dir"
          clean: false
      - uses: ./.github/actions/test
        with:
          env: "dev"

  deploy-to-staging:
    runs-on: self-hosted
    needs: [tests-on-dev]
    steps:
      - uses: actions/checkout@v3.5.2
        with:
          clean: false
      - uses: actions/checkout@v3.5.2
        with:
          repository: "mtararujs/python-greetings"
          path: "deploy-dir"
          clean: false
      - uses: ./.github/actions/deploy
        with:
          port: 7002
          env: "staging"

  tests-on-staging:
    runs-on: self-hosted
    needs: [deploy-to-staging]
    steps:
      - uses: actions/checkout@v3.5.2
        with:
          clean: false
      - uses: actions/checkout@v3.5.2
        with:
          repository: "mtararujs/course-js-api-framework"
          path: "test-dir"
          clean: false
      - uses: ./.github/actions/test
        with:
          env: "staging"

  deploy-to-preprod:
    runs-on: self-hosted
    needs: [tests-on-staging]
    steps:
      - uses: actions/checkout@v3.5.2
        with:
          clean: false
      - uses: actions/checkout@v3.5.2
        with:
          repository: "mtararujs/python-greetings"
          path: "deploy-dir"
          clean: false
      - uses: ./.github/actions/deploy
        with:
          port: 7003
          env: "preprod"

  tests-on-preprod:
    runs-on: self-hosted
    needs: [deploy-to-preprod]
    steps:
      - uses: actions/checkout@v3.5.2
        with:
          clean: false
      - uses: actions/checkout@v3.5.2
        with:
          repository: "mtararujs/course-js-api-framework"
          path: "test-dir"
          clean: false
      - uses: ./.github/actions/test
        with:
          env: "preprod"
  deploy-to-prod:
    runs-on: self-hosted
    needs: [tests-on-preprod]
    steps:
      - uses: actions/checkout@v3.5.2
        with:
          clean: false
      - uses: actions/checkout@v3.5.2
        with:
          repository: "mtararujs/python-greetings"
          path: "deploy-dir"
          clean: false
      - uses: ./.github/actions/deploy
        with:
          port: 7004
          env: "prod"

  tests-on-prod:
    runs-on: self-hosted
    needs: [deploy-to-prod]
    steps:
      - uses: actions/checkout@v3.5.2
        with:
          clean: false
      - uses: actions/checkout@v3.5.2
        with:
          repository: "mtararujs/course-js-api-framework"
          path: "test-dir"
          clean: false
      - uses: ./.github/actions/test
        with:
          env: "prod"
